/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ibm.mq.client;

import org.junit.Test;
import static org.junit.Assert.*;

public class IbmMqClientApplicationTest {
    @Test public void appHasAGreeting() {
        IbmMqClientApplication classUnderTest = new IbmMqClientApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
