/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ibm.mq.client;

public class IbmMqClientApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new IbmMqClientApplication().getGreeting());
    }
}
